### ISSUE TITLE
Adding published_till

### ISSUE THREAD

**Issue by olliecamp** [pawelmysior/laravel-publishable#1]
Have you thought about adding a published_till variant as well.

You could schedule a model to be visible only during those two dates and after consider it an "archive"?

**Comment by pawelmysior** [comment]
Hi @rockfreak, thanks for using the package. I haven't thought about adding a published_till field, because I've never had a situation in which I would need this functionality. I use this package just for situations like publishing a post on a blog, where you want to have the ability to keep it unpublished until a certain date.

Adding the functionality that you mention is outside of the scope of this package. You can easily fork the repo and create your own version though :)

Regards!
